name: Reusable
on:
  workflow_call:
    inputs:
      artifact:
        description: The name of deployable artifacts
        required: false
        default: dist
        type: string
    outputs:
      result:
        description: The result of the deployment
        value: ${{ jobs.deploy.outputs.outcome }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      outcome: ${{ steps.set-result.outputs.result }}

    steps:
      - name: Get code
        uses: actions/download-artifact@v5
        with:
          name: ${{ inputs.artifact }}

      - name: List files
        run: ls

      - name: Output Information
        run: echo 'Deploying and uploading'

      - name: Set result output
        id: set-result
        run: echo "result=success" >> $GITHUB_OUTPUT
