name: Reusable
on:
  workflow_call:
    inputs:
      artifact:
        description: The name of deployable artifacts
        required: false
        default: dist
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/download-artifact@v5
        with:
          name: ${{ inputs.artifact }}

      - name: List files
        run: ls

      - name: Output Information
        run: echo 'Deploying and uploading'
